FROM ubuntu:focal
# focal currently has node 10, which the cairo dependency of onetech depends on (or maybe < 10 as well)

RUN mkdir -p /home/jcr13/checkout

copy . /home/jcr13/

WORKDIR /home/jcr13/
